dorostkon/bamehran/SocialMedia/SocialMedia/urls.py
from django.contrib import admin
from django.urls import path, include
from weblog.views import logout_view
#from django.contrib.auth import logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('weblog.urls')),
    path('logout/' , logout_view , name='logout'),
]




from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dorostkon/bamehran/SocialMedia/weblog/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'weblog'
urlpatterns = [
    path('', views.home, name='home'),
    path('article/<slug:slug>/', views.detail, name='detail'),
    #The <slug:slug> part is a URL parameter capturing a slug and passing it to the detail view. So, when a user visits a URL like "/article/some-example-slug/", Django captures "some-example-slug" and passes it as the slug parameter to the detail view.
    #path('koskalak/', views.koskalak, name='koskalak'),
    path('about/' , views.aboutsiteview , name='about' ),
    path('sabtenam/', views.form_registering_view, name='sabtenam'),
    path('loginG/', views.form_registering_view, name='loginG'),
]
     

dorostkon/bamehran/SocialMedia/weblog/models.py
from django.db import models
from django.utils import timezone
from extensions.utils import jalali_converter
# Create your models here.
class Category(models.Model):
    title=models.CharField(max_length=100, verbose_name='عنوان دسته بندی')
    slug=models.SlugField(max_length=100, unique=True, verbose_name='ادرس دسته بندی')
    status=models.BooleanField(default=True , verbose_name='ایا نمایش داده شود؟')
    position=models.IntegerField(verbose_name='پوزیشن')
    class Meta:
        verbose_name='دسته بندی'
        verbose_name_plural='دسته بندی ها'
        ordering= ['position']
    def __str__(self):
        return self.title

class Article(models.Model):
    
    STATUS_CHOICES=(
        ('d' , 'Draft'),
        ('p' , 'Publish'),
    )
    title=models.CharField(max_length=200, verbose_name='عنوان مقاله')
    slug=models.SlugField(max_length=100, unique=True, verbose_name='ادرس مقاله')
    category=models.ManyToManyField(Category, verbose_name='دسته بندی')
    description=models.TextField( verbose_name='محتوا')
    thumbnail=models.ImageField(upload_to="images", verbose_name='تصویر مقاله')
    publish=models.DateTimeField(default=timezone.now, verbose_name='زمان انتشار مقاله')
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    status=models.CharField(max_length=1 , choices=STATUS_CHOICES , verbose_name='وضعیت')
    
    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural ='مقالات'    
    def __str__(self):
        return self.title
    
    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description = "زمان انتشار"
    


class RegisteringModel(models.Model):
    first_name=models.CharField(max_length=30, verbose_name='نام')
    last_name=models.CharField(max_length=80, verbose_name='نام خانوادگی')
    birth_date=models.DateField(auto_now=True)
    phone_number=models.CharField(max_length=12 , verbose_name='شماره تلفن همراه')
    email_address=models.EmailField(null=True, blank=True , verbose_name='ایمیل')
    address=models.CharField(max_length=200)
    def __str__(self):
        return f'{self.first_name} {self.last_name}'

dorostkon/bamehran/SocialMedia/weblog/forms.py
from django import forms
from .models import RegisteringModel


class RegisteringForm(forms.ModelForm):
    class Meta:
        model=RegisteringModel
        fields= '__all__'

dorostkon/bamehran/SocialMedia/weblog/views.py
from django.shortcuts import render , get_object_or_404, redirect
from .models import Article
from .forms import RegisteringForm
from django.contrib.auth import logout

# Create your views here.
def home(request):
    context={
        "articles": Article.objects.all().order_by('publish')
    }
    return render(request , 'weblog/base.html' ,context )

def detail(request , slug):
    #In this line, slug is a parameter of the detail function. When you define a view function in Django, it often takes parameters that represent information extracted from the URL. In this case, slug is likely to be part of the URL for this view.
    context={
         "article" : get_object_or_404(Article , slug=slug)
         
#ghbln in bod bjay balai__>  "article" : Article.objects.get(slug=slug)
    }
    return render(request , 'weblog/detail.html' , context)

#def koskalak(request):
#    return render(request, 'blog/base.html')


def aboutsiteview(request):
    return render(request , 'weblog/about.html')


def form_registering_view(request):
    form=RegisteringForm()
    if request.method=='POST': 
        form = RegisteringForm(request.POST)   
        if form.is_valid():
            form.save()
    context={"form":form} 
    return render(request, 'weblog/reg.html', context)    
    
    
    
    
def logout_view (request):
    logout(request)
    return redirect(request.GET.get('next'))

dorostkon/bamehran/SocialMedia/weblog/templates/weblog/about.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Grayscale - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}" /> 
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">


        <!-- About-->
        <section class="about-section text-center" id="down">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8">
                        <h2 class="text-white mb-4">به وبسایت خبری غزل موآ خیلی خیلی خیلی زیاد خوش اومدین</h2>
                        <p class="text-white-50">
                            اینجا قراره که باهمدیگه کلی خبر راجب خوادث و سلبریتیا بخونیم شاید یه سری تحلیل سیاسی و اقتصادی هم گذاشتم
                             اگه خواستی منبع خبری مو ببینی
                            <a href="https://www.rokna.net/">اینجا کلیک کن</a>
                           بریم داغ ترین خبرهای امروز رو ببینیم
                        </p>
                    </div>
                </div>
                <img class="img-fluid" src="{% static 'img/bluish-grey-smokey-eye-1.jpg' %}" alt="..." />
                

            </div>
        </section>
    </body>
</html>        

dorostkon/bamehran/SocialMedia/weblog/templates/weblog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>ghazalMUA</title>
        <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}" /> 
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#page-top">غزل موآ</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'weblog:about' %}">درباره ما</a></li>
                        <li class="nav-item"><a class="nav-link" href="{%url 'weblog:sabtenam' %}">ثبت نام</a></li>
                        <li class="nav-item"><a class="nav-link" href="#signup">تماس با ما</a></li>
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                                <span >خوش آمدی {{user.get_full_name}} عزیز , <a href="{% url 'logout' %}?next={{request.path}}"  >خروج</a></span>
                            {% else %}
                                <a href="{% url 'weblog:sabtenam' %}" class="btn btn-dsanger" >لاگین/ثبت نام با گوگل</a>
                            {% endif %}
                        </li>
                    <!--   <li class="nav-item"><a class="nav-link" href="">خروج</a></li> --> 
                    <!--    <li class="nav-item"><a class="btn" href="{%url 'weblog:loginG' %}">لاگین با گوگل</a></li> -->
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
                <div class="d-flex justify-content-center">
                    <div class="text-center">
                        <h1 class="mx-auto my-0 text-uppercase">خبرهای زرد دسته اول</h1>
                        <h2 class="text-white-50 mx-auto mt-2 mb-5">هر موقع دوست داشتی خاله زنکی کنی بیا اینجا</h2>
                        <a class="btn btn-primary" href="#about">بزن بریم</a>
                    </div>
                </div>
            </div>
        </header>
        <!-- About-->
        <section class="about-section text-center" id="about">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8">
                        <h2 class="text-white mb-4">به وبسایت خبری غزل موآ خیلی خیلی خیلی زیاد خوش اومدین</h2>
                        <p class="text-white-50">
                            اینجا قراره که باهمدیگه کلی خبر راجب خوادث و سلبریتیا بخونیم شاید یه سری تحلیل سیاسی و اقتصادی هم گذاشتم
                             اگه خواستی منبع خبری مو ببینی
                            <a href="https://www.rokna.net/">اینجا کلیک کن</a>
                           بریم داغ ترین خبرهای امروز رو ببینیم
                        </p>
                    </div>
                </div>
                <img class="img-fluid" src="{% static 'img/ipad.png' %}" alt="..." />
            </div>
        </section>
        <!-- Projects-->
        <section class="projects-section bg-light" id="projects">
            <div class="container px-4 px-lg-5">
                <!-- Featured Project Row-->
                <div class="row gx-0 mb-4 mb-lg-5 align-items-center">
                    <div class="col-xl-8 col-lg-7"><img class="img-fluid mb-3 mb-lg-0" src="{% static 'img/bg-masthead.jpg' %}" alt="..." /></div>
                    <div class="col-xl-4 col-lg-5">
                        <div class="featured-text text-center text-lg-left">
                            <h4>Shoreline</h4>
                            <p class="text-black-50 mb-0">Grayscale is open source and MIT licensed. This means you can use it for any project - even commercial projects! Download it, customize it, and publish your website!</p>
                        </div>
                    </div>
                </div>
                <!-- Project One Row-->
                <div class="row gx-0 mb-5 mb-lg-0 justify-content-center">
                    <div class="col-lg-6"><img class="img-fluid" src="{% static 'img/demo-image-01.jpg' %}" alt="..." /></div>
                    <div class="col-lg-6">                      
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-left">
                                    <h4 class="text-white">Misty</h4>
                                    <p class="mb-0 text-white-50">An example of where you can put an image of a project, or anything else, along with a description.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Project Two Row-->
                <div class="row gx-0 justify-content-center">      
                    <div class="col-lg-6"><img class="img-fluid" src="{% static 'img/demo-image-02.jpg' %}" alt="..." /></div>
                    <div class="col-lg-6 order-lg-first">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-right">
                                    <h4 class="text-white">Mountains</h4>
                                    <p class="mb-0 text-white-50">Another example of a project with its respective description. These sections work well responsively as well!</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Signup-->
        <section class="signup-section" id="signup">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5">
                    <div class="col-md-10 col-lg-8 mx-auto text-center">
                        <i class="far fa-paper-plane fa-2x mb-2 text-white"></i>
                        <h2 class="text-white mb-5">Subscribe to receive updates!</h2>
                        <!-- * * * * * * * * * * * * * * *-->
                        <!-- * * SB Forms Contact Form * *-->
                        <!-- * * * * * * * * * * * * * * *-->
                        <!-- This form is pre-integrated with SB Forms.-->
                        <!-- To make this form functional, sign up at-->
                        <!-- https://startbootstrap.com/solution/contact-forms-->
                        <!-- to get an API token!-->
                        <form class="form-signup" id="contactForm" data-sb-form-api-token="API_TOKEN">
                            <!-- Email address input-->
                            <div class="row input-group-newsletter">
                                <div class="col"><input class="form-control" id="emailAddress" type="email" placeholder="Enter email address..." aria-label="Enter email address..." data-sb-validations="required,email" /></div>
                                <div class="col-auto"><button class="btn btn-primary disabled" id="submitButton" type="submit">Notify Me!</button></div>
                            </div>
                            <div class="invalid-feedback mt-2" data-sb-feedback="emailAddress:required">An email is required.</div>
                            <div class="invalid-feedback mt-2" data-sb-feedback="emailAddress:email">Email is not valid.</div>
                            <!-- Submit success message-->
                            <!---->
                            <!-- This is what your users will see when the form-->
                            <!-- has successfully submitted-->
                            <div class="d-none" id="submitSuccessMessage">
                                <div class="text-center mb-3 mt-2 text-white">
                                    <div class="fw-bolder">Form submission successful!</div>
                                    To activate this form, sign up at
                                    <br />
                                    <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                </div>
                            </div>
                            <!-- Submit error message-->
                            <!---->
                            <!-- This is what your users will see when there is-->
                            <!-- an error submitting the form-->
                            <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3 mt-2">Error sending message!</div></div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!-- Contact-->
        <section class="contact-section bg-black">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5">
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-map-marked-alt text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Address</h4>
                                <hr class="my-4 mx-auto" />
                                <div class="small text-black-50">4923 Market Street, Orlando FL</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-envelope text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Email</h4>
                                <hr class="my-4 mx-auto" />
                                <div class="small text-black-50"><a href="#!">hello@yourdomain.com</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-mobile-alt text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Phone</h4>
                                <hr class="my-4 mx-auto" />
                                <div class="small text-black-50">+1 (555) 902-8832</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="social d-flex justify-content-center">
                    <a class="mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                    <a class="mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                    <a class="mx-2" href="#!"><i class="fab fa-github"></i></a>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="footer bg-black small text-center text-white-50"><div class="container px-4 px-lg-5">Copyright &copy; Your Website 2023</div></footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

dorostkon/bamehran/SocialMedia/weblog/templates/weblog/reg.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration Form</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .registration-container {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
            width: 400px;
            max-width: 100%;
            box-sizing: border-box;
        }

        h2 {
            text-align: center;
            color: #333;
        }

        form {
            display: flex;
            flex-direction: column;
        }

        label {
            margin-bottom: 8px;
            font-weight: bold;
            color: #555;
        }

        input {
            padding: 10px;
            margin-bottom: 16px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
            box-sizing: border-box;
        }

        button {
            background-color: #4caf50;
            color: #fff;
            padding: 12px;
            border: none;
            border-radius: 4px;
            font-size: 16px;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <div class="registration-container">
        <h2>فرم ثبت نام در سایت خاله زنکی غزل موآ</h2>
        <form action="{% url 'weblog:sabtenam' %}" method="post">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>

            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required>

            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>

            <button type="submit">Register</button>
        </form>
    </div>
</body>
</html>

<head>
    <title>ثبت نام</title>
  </head>
  <body>
  
    <h2>ثبت نام</h2>
  
    <form method="post" action="{% url 'weblog:sabtenam' %}">
       {% csrf_token %}
       {{ form.as_p }}
       <input type="submit">دکمه را فشار دهید</button>
    </form> -->




<!--
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Registration Form</title>
        <style>
            body {
                font-family: 'Arial', sans-serif;
                background-color: #f4f4f4;
                margin: 0;
                padding: 0;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
            }
    
            .registration-container {
                background-color: #fff;
                border-radius: 8px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
                padding: 20px;
                width: 400px;
                max-width: 100%;
                box-sizing: border-box;
            }
    
            h2 {
                text-align: center;
                color: #333;
            }
    
            form {
                display: flex;
                flex-direction: column;
            }
    
            label {
                margin-bottom: 8px;
                font-weight: bold;
                color: #555;
            }
    
            input {
                padding: 10px;
                margin-bottom: 16px;
                border: 1px solid #ccc;
                border-radius: 4px;
                font-size: 16px;
                box-sizing: border-box;
            }
    
            button {
                background-color: #4caf50;
                color: #fff;
                padding: 12px;
                border: none;
                border-radius: 4px;
                font-size: 16px;
                cursor: pointer;
            }
    
            button:hover {
                background-color: #45a049;
            }
        </style>
    </head>
    <body>
        <div class="registration-container">
            <h2>فرم ثبت نام</h2>
            <p>لطفا اطلاغات خود را با دقت وارد کنید</p>
            <form method="post" action="{%url 'weblog:sabtenam' %}">
                {% csrf_token %}
                <label for="first_name">First Name:</label>
                <input type="text" id="name" name="نام" required>
    
                <label for="last_name">Last Name:</label>
                <input type="text" id="last_name" name="نام خانوادگی" required>
    
                <label for="birth_date">Birth Date:</label>
                <input type="date"  id="birth_date" name="تاریخ تولد"required>
    
                <label for="phone_number">Phone Number:</label>
                <input type="tel" id="phone_number" name="تلفن همراه" required>
    
                <label for="email_address">Email Address:</label>
                <input type="email" id="email_address" name="ایمیل">
    
                <label for="address">Address:</label>
                <input type="text" id="address" name="آدرس" required>
    
                <button type="submit">ثبت نام</button>
            </form>
        </div>
    </body>
    </html>
-->



<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ثبت نام</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .registration-container {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
            width: 400px;
            max-width: 100%;
            box-sizing: border-box;
        }

        h2 {
            text-align: center;
            color: #333;
        }

        form {
            display: flex;
            flex-direction: column;
        }

        label {
            margin-bottom: 8px;
            font-weight: bold;
            color: #555;
        }

        input {
            padding: 10px;
            margin-bottom: 16px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
            box-sizing: border-box;
        }

        button {
            background-color: #4caf50;
            color: #fff;
            padding: 12px;
            border: none;
            border-radius: 4px;
            font-size: 16px;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }
    </style>
</head>

<body>
    <div class="registration-container">
        <h2>ثبت نام</h2>
        <p>لطفا اطلاعات خود را با دقت وارد کنید</p>
        <form method="post" action="{% url 'weblog:sabtenam' %}">
            {% csrf_token %}
            <label for="{{ form.first_name.id_for_label }}">First Name:</label>
            {{ form.first_name }}
    
            <label for="{{ form.last_name.id_for_label }}">Last Name:</label>
            {{ form.last_name }}
    
            <label for="{{ form.birth_date.id_for_label }}">Birth Date:</label>
            {{ form.birth_date }}
    
            <label for="{{ form.phone_number.id_for_label }}">Phone Number:</label>
            {{ form.phone_number }}
    
            <label for="{{ form.email_address.id_for_label }}">Email Address:</label>
            {{ form.email_address }}
    
            <label for="{{ form.address.id_for_label }}">Address:</label>
            {{ form.address }}
    
            <button type="submit">ثبت نام</button>
        </form>
    </div>
</body>

</html>

dorostkon/bamehran/SocialMedia/weblog/templates/weblog/regist.html
<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
  <title>ثبت نام</title>
</head>
<body>

  <h2>ثبت نام</h2>

  <form method="post" action="{% url 'weblog:sabtenam' %}">
     {% csrf_token %}
     {{ form.as_p }}
     <input type="submit">دکمه را فشار دهید</button>

  <!--   <button class="btn" onclick="window.location.href='{% url 'weblog:loginG' %}'">لاگین با گوگل</button>
-->       
<button class="btn" id="loginButton">لاگین با گوگل</button>

<script type="text/javascript">
    document.getElementById('loginButton').addEventListener('click', function() {
        window.location.href = "{% url '' %}";
    });
</script>
         
  </form>
  
</body>
</html>