DjangoEcommerce/A/A/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls' , namespace='home')),
]

DjangoEcommerce/A/home/urls.py
from django.urls import path
from . import views

app_name='home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('navbar' , views.navbarview),
    path('base' , views.baseview)

]

DjangoEcommerce/A/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser


class User(AbstractBaseUser):
    email =models.EmailField(max_length=255, unique=True)
    phone_number =models.CharField(max_length=11 , unique=True)
    full_name= models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    USERNAME_FIELD = 'phone_number'       #fieldi ke mikhay user ro bahash etebar sanji bokoni , harchiziz inja gozashtim bayad tooye ghesmati ke tarifesh kardim unique esh true bashe
    
    REQUIRED_FIELDS = ['email' , 'full_name']           #fieldi ke mikhay  vaghti dari az dasture python manage.py createsuper user miani azat beporse

    def __str__(self):
        return self.email
    
    def has_perm(self,perm,pbj=None):
        return True
    
    def has_module_perms(self, app_lable):
        return True
    
    @property
    def is_staff(self):
        return self.is_admin

DjangoEcommerce/A/home/models.py
from django.db import models

# Create your models here.

DjangoEcommerce/A/accounts/views.py
from django.shortcuts import render

# Create your views here.

DjangoEcommerce/A/home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View


class HomeView(View):
    def get(self, request):
        return render(request, template_name='home/home.html')
    
def navbarview(request):
    return render (request, 'inc/navbar.html')    

def baseview(request):
    return render (request, 'base.html')    

DjangoEcommerce/A/home/templates/home/home.html
<h1>hello user</h1>

DjangoEcommerce/A/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Online Shop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        .jumbotron{
            padding: 20px;
            margin-bottom: 20px;
            background-color: #e9eccf;
        }
    </style>
</head>
<body>

    {% include 'inc/navbar.html' %}
    <div class="jumbotron">
        {% include 'inc/messages.html' %}
        {% block content %} {% endblock %}
    </div>


</body>
</html>

DjangoEcommerce/A/templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

DjangoEcommerce/A/templates/inc/navbar.html
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'home:home' %}">Home</a>
            <a class="nav-link active" href="{% url 'home:home' %}">ghazal</a>
            <a class="nav-link active" href="{% url 'home:home' %}">bardia</a>
            <a class="nav-link active" href="{% url 'home:home' %}">amiroooo</a>

        </div>
    </div>
</nav>